-- CreateTable
CREATE TABLE `_CATEGORIAS_ARTICULOS` (
    `A` INTEGER NOT NULL,
    `B` INTEGER NOT NULL,

    UNIQUE INDEX `_CATEGORIAS_ARTICULOS_AB_unique`(`A`, `B`),
    INDEX `_CATEGORIAS_ARTICULOS_B_index`(`B`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `_CATEGORIAS_ARTICULOS` ADD CONSTRAINT `_CATEGORIAS_ARTICULOS_A_fkey` FOREIGN KEY (`A`) REFERENCES `Articulo`(`id_articulo`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `_CATEGORIAS_ARTICULOS` ADD CONSTRAINT `_CATEGORIAS_ARTICULOS_B_fkey` FOREIGN KEY (`B`) REFERENCES `Categoria`(`id_categoria`) ON DELETE CASCADE ON UPDATE CASCADE;
